name: kaboom_dart
description: The Kaboom Dart package
version: 1.0.0
homepage: https://github.com/kaboom-db/kaboom-dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.4
